version: '3.6'
services:
  postgres:
    restart: always
    # network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
volumes:
  db_data:


