"""Update reward type

Revision ID: 5f55afa034f3
Revises: cb8471cda155
Create Date: 2023-05-28 14:31:05.174496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f55afa034f3'
down_revision = 'cb8471cda155'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('governance_proposal', 'reward',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=38, scale=0),
               existing_nullable=True)
    op.create_index('governance_proposal_reward_idx', 'governance_proposal', ['reward'], unique=False)
    op.create_index('governance_proposal_status_idx', 'governance_proposal', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('governance_proposal_status_idx', table_name='governance_proposal')
    op.drop_index('governance_proposal_reward_idx', table_name='governance_proposal')
    op.alter_column('governance_proposal', 'reward',
               existing_type=sa.Numeric(precision=38, scale=0),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
