"""Added on chain properties

Revision ID: cb8471cda155
Revises: b624da80421b
Create Date: 2023-05-26 18:53:58.165223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8471cda155'
down_revision = 'b624da80421b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('governance_proposal', sa.Column('reward', sa.BigInteger(), nullable=True))
    op.add_column('governance_proposal', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('governance_proposal', 'status')
    op.drop_column('governance_proposal', 'reward')
    # ### end Alembic commands ###
